- name: "area/root"
  color: "8D6E63"
  description: "A change in the root of the directory."

- name: "area/ci"
  color: "6A1B9A"
  description: "A CI change."

- name: "type/bug"
  color: "d73a4a"
  description: "Something isn't working as expected."

- name: "type/enhancement"
  color: "a2eeef"
  description: "A new feature or improvement to existing functionality."

- name: "type/documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation."
  aliases:
    - "docs"
    - "documentation"

- name: "status/triage"
  color: "b60205"
  description: "Issue needs triage."

- name: "status/in-progress"
  color: "0e8a16"
  description: "Being actively worked on"

- name: "status/awaiting-response"
  color: "fbca04"
  description: "Awaiting user response."

- name: "status/stale"
  color: "eeeeee"
  description: "Stale."

- name: "good first issue"
  color: "7057ff"
  description: "A good issue for new contributors."
  
- name: "release"
  color: "000000"
  description: "A release label."
