#!/usr/bin/env bash

# ==============================================================================
# Script: prepare-release.sh
# Description: Prepares the repository for a semantic-release.
#              The CHANGELOG.md is generated but not committed to main.
#
# Usage: ./prepare-release.sh <version>
# ==============================================================================

set -euo pipefail

VERSION="${1:-}"

if [[ -z "$VERSION" ]]; then
    echo "Error: Version argument is required."
    echo "Usage: ./prepare-release.sh <version>"
    exit 1
fi

echo "Preparing release for version: $VERSION"

# Remove 'v' prefix if present
VERSION="${VERSION#v}"

# The CHANGELOG.md has been generated by semantic-release
# We'll include it in the detached release commit but not push to main
echo "CHANGELOG.md generated and ready for release"

echo "Preparation complete for version: $VERSION"

