#!/usr/bin/env bash

# ==============================================================================
# Script: publish-release.sh
# Description: Publishes the release using the existing release.sh script
#              and creates a PR to bump the version on main branch.
#
# Usage: RELEASE_NOTES="..." ./publish-release.sh <version>
# Env Vars: 
#   - GITHUB_TOKEN (Required for gh cli)
#   - RELEASE_NOTES (Release notes content)
# ==============================================================================

set -euo pipefail

VERSION="${1:-}"

if [[ -z "$VERSION" ]]; then
    echo "Error: Version argument is required."
    echo "Usage: RELEASE_NOTES=\"...\" ./publish-release.sh <version>"
    exit 1
fi

# Remove 'v' prefix if present for version parsing
VERSION_NUM="${VERSION#v}"

echo "Publishing release for version: $VERSION"

# Configure git
git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

# Stage and commit the CHANGELOG.md to include it in the detached commit
if [[ -f "CHANGELOG.md" ]]; then
    echo "Staging CHANGELOG.md for detached commit..."
    git add CHANGELOG.md
    git commit -m "chore: update changelog for ${VERSION}" || echo "No changelog changes to commit"
fi

# Create snapshot tag on main branch (for semantic-release to track)
SNAPSHOT_TAG="snapshot-v${VERSION_NUM}"
echo "Creating snapshot tag ${SNAPSHOT_TAG} on main branch..."
if git rev-parse "$SNAPSHOT_TAG" >/dev/null 2>&1; then
    echo "Snapshot tag already exists, deleting..."
    git tag -d "$SNAPSHOT_TAG"
    git push origin ":refs/tags/$SNAPSHOT_TAG" 2>/dev/null || true
fi
git tag "$SNAPSHOT_TAG"
git push origin "$SNAPSHOT_TAG"

# Run the existing release script (creates detached commit, tags, and releases)
echo "Creating detached release..."
./.github/scripts/release.sh "$VERSION_NUM" "$RELEASE_NOTES"

# Parse version components
IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION_NUM"

# Checkout main branch to bump version
echo "Checking out main branch..."
git fetch origin main
git checkout main
git pull origin main

# Calculate next version
NEXT_PATCH=$((PATCH + 1))
NEXT_VERSION="${MAJOR}.${MINOR}.${NEXT_PATCH}-SNAPSHOT"

# Create a branch for the version bump
BRANCH_NAME="chore/bump-version-${NEXT_VERSION}"
git checkout -b "$BRANCH_NAME"

# Bump to next snapshot version
echo "Bumping to next snapshot version..."
./.github/scripts/bump-version.sh "$MAJOR" "$MINOR" "$PATCH"

# Commit the version bump
echo "Committing version bump..."
git add version.go
git commit -m "chore: bump version to ${NEXT_VERSION}"
git push origin "$BRANCH_NAME"

# Create PR using GitHub CLI
echo "Creating pull request..."
gh pr create \
    --title "chore: bump version to ${NEXT_VERSION}" \
    --body "Bumps version to ${NEXT_VERSION} after release of v${VERSION_NUM}.

Auto-generated by semantic-release." \
    --base main \
    --head "$BRANCH_NAME"

echo "Release published and PR created for version bump!"

