name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["type/enhancement", "status/triage"]
body:
- type: textarea
  id: problem
  attributes:
    label: Problem Statement
    description: What problem does this feature solve?
    placeholder: "As a [user type], I want [goal] so that [benefit]"
  validations:
    required: true
- type: textarea
  id: proposed-solution
  attributes:
    label: Proposed Solution
    description: How would you solve this problem?
  validations:
    required: true
- type: textarea
  id: alternatives
  attributes:
    label: Alternatives Considered
    description: What alternative solutions or workarounds have you considered?
- type: dropdown
  id: breaking-change
  attributes:
    label: Breaking Change
    description: Would this require breaking API changes?
    options:
      - "No"
      - "Yes"
      - "Unsure"
  validations:
    required: true
- type: textarea
  id: use-case
  attributes:
    label: Use Case
    description: Describe your use case in detail
- type: checkboxes
  id: contribution
  attributes:
    label: Contribution
    options:
      - label: I am willing to submit a PR for this feature
